name: Deploy cache

on: push
concurreny:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    #Los jobs y workflows pueden cancelarse y  definirse aa nivel  job, step o  workflow
    #https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobshttps://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: CAche  dependencias
        uses:  actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os}}-node-modules-${{ hashFiles('package-lock.json') }}
          #  las restore keys se recomienda es usarlas ssolo la primera seccion que es fija, doc importante: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows
          restore-keys: |
            ${{ runner.os}}-node-modules-

      - name: Instalar dependencias
        run: npm install
      
      - name: Run test
        run: npm run test
      - name: HOla
        run:  echo "hola prueba no concurrencia solucionado" >>$GITHUB_STEP_SUMMARY
      - name: Build page
        run: npm run build
#Esto es para ver mas informacion durantte los logs

#       ACTIONS_RUNNER_DEBUG
	
# true
	
# Jun 19, 2025
	
# ACTIONS_STEP_DEBUG
	
# true