name: Deploy

on: 
  push:
    branches:
      - main
      - stage


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: setup SHH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.SSH_KEY}}

      - name: deploy to stage server
        if: ${{ github.ref == 'refs/heads/stage' }}
        run: bash deploy.sh stage

      - name: deploy to prd server
        if: ${{ github.ref == 'refs/heads/main' }}
        run: bash deploy.sh main